name: check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 25.3
          - 26.3
    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: leotaku/elisp-check@master
        with:
          check: melpa
          file: 'npm.el'
          ignore_warnings: false
          warnings_as_errors: false
